# Generated by Django 4.1.6 on 2024-01-11 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0044_alter_games_created_at_alter_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_infos',
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 31, 42, 923419, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 31, 42, 923419, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 31, 42, 923419, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.CreateModel(
            name='Round1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.CharField(max_length=100, null=True, verbose_name='Numéro du round')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 31, 42, 924931, tzinfo=datetime.timezone.utc), verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.CharField(max_length=20, null=True, verbose_name='Joueur 1')),
                ('player1_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('player2', models.CharField(max_length=20, null=True, verbose_name='Joueur 2')),
                ('player2_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('player3', models.CharField(max_length=20, null=True, verbose_name='Joueur 3')),
                ('player3_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('player4', models.CharField(max_length=20, null=True, verbose_name='Joueur 4')),
                ('player4_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('player5', models.CharField(max_length=20, null=True, verbose_name='Joueur 5')),
                ('player5_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('player6', models.CharField(max_length=20, null=True, verbose_name='Joueur 6')),
                ('player6_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('player7', models.CharField(max_length=20, null=True, verbose_name='Joueur 7')),
                ('player7_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('player8', models.CharField(max_length=20, null=True, verbose_name='Joueur 8')),
                ('player8_score', models.IntegerField(max_length=8, null=True, verbose_name='Score joueur 1')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament', verbose_name='Tournoi')),
            ],
        ),
    ]
