# Generated by Django 4.1.6 on 2024-01-11 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0046_alter_games_created_at_alter_round1_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round1',
            name='round_number',
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 50, 56, 774226, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 50, 56, 775231, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 50, 56, 774226, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 15, 50, 56, 773351, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
