# Generated by Django 4.1.6 on 2024-02-08 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0049_alter_games_created_at_alter_round1_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 0, 0, 857150, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 0, 0, 858149, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 0, 0, 858149, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 0, 0, 857150, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 11, 0, 0, 856140, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
