# Generated by Django 4.1.6 on 2024-02-08 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0051_alter_games_created_at_alter_round1_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round1',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Round ouvert'),
        ),
        migrations.AddField(
            model_name='round2',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Round ouvert'),
        ),
        migrations.AddField(
            model_name='round3',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Round ouvert'),
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 23, 38, 827748, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 23, 38, 834277, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 23, 38, 835390, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='round3',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 23, 38, 835390, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 23, 38, 827748, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 15, 23, 38, 827748, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
