# Generated by Django 4.1.6 on 2024-06-08 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0052_round1_open_round2_open_round3_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 13, 1, 2, 847119, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='round1',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 13, 1, 2, 848122, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 13, 1, 2, 848122, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='round3',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 13, 1, 2, 848627, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 13, 1, 2, 847119, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 13, 1, 2, 847119, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
